language: cpp
dist: trusty
sudo: true

compiler:
  - clang
  - gcc

env:
  global:
    - CXXFLAGS="-O0 -g"
  matrix:
    - PHPVER=7.0
    - PHPVER=7.1

matrix:
  include:
    - compiler: gcc
      env: NOPCH=1 PHPVER=7.0 CXXFLAGS="-O0 -g"
    - compiler: gcc
      env: NOPCH=1 PHPVER=7.1 CXXFLAGS="-O0 -g"

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq update
  - sudo apt-get -qq install valgrind libgtest-dev libphp$PHPVER-embed php$PHPVER-dev

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh
