language: cpp
dist: trusty
sudo: true

compiler:
  - clang
  - gcc

env:
  - PHPVER=7.0
  - PHPVER=7.1

matrix:
  include:
    - compiler: gcc
      env: PHPCXX_CPPFLAGS_PCH= TESTER_CPPFLAGS_PCH= PHPVER=7.0
    - compiler: gcc
      env: PHPCXX_CPPFLAGS_PCH= TESTER_CPPFLAGS_PCH= PHPVER=7.1
  exclude:
    - compiler: clang
      env: PHPVER=7.1
  allow_failures:
    - env: PHPVER=7.1

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq update
  - sudo apt-get -qq install valgrind libgtest-dev libphp$PHPVER-embed php$PHPVER-dev

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh
