language: cpp
dist: trusty
sudo: true

compiler:
  - clang
  - gcc

env:
  global:
    - CXXFLAGS="-O0 -g"
  matrix:
    - PHPVER=7.0
    - PHPVER=7.1

matrix:
  include:
    - compiler: gcc
      env: NOPCH=1 PHPVER=7.0 CXXFLAGS="-O2 -g"
    - compiler: gcc
      env: NOPCH=1 PHPVER=7.1 CXXFLAGS="-O2 -g"

before_install:
  - ./.travis/before_install.sh

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh
